version: "3.8"

services:
  vue-app:
    build:
      context: ./  # Path to your frontend folder
      dockerfile: dockerfile  # Reference to the Dockerfile in the frontend folder
    container_name: vue-app
    ports:
      - "8081:80"  # Expose port 8081 on the host and map it to port 80 inside the container (NGINX default)
